---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mockbin
  labels:
    app: mockbin
    app.kubernetes.io/name: mockbin
    app.kubernetes.io/component: api
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.mockbin: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"mockbin"}}'

